export enum ActionType {
    GET_POSTS = 'GET_POSTS',
    GET_CURRENT_POSTS="GET_CURRENT_POSTS",
    GET_POSTS_BY_ID = 'GET_POSTS_BY_ID',
    FILTER_AND_SORT = 'FILTER_AND_SORT',
    SET_IS_MODAL_OPEN = 'SET_IS_MODAL_OPEN'
}